project:
  type: book
  render:
    - index.qmd
    - 1_preprocess.qmd
    - 2_basicNeeds.qmd
    - 3_sleep.qmd
  output-dir: outputs
book:
  title: "Relationships Between Health and Logged Video Game Play Across Platforms"
  author: "Digital Wellbeing Lab"
  chapters:
    - index.qmd
    - 1_preprocess.qmd
    - 2_basicNeeds.qmd
    - 3_sleep.qmd
toc: true
editor_options:
  chunk_output_type: console
execute:
  warning: false
page-layout: full
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: cosmo
bibliography: references.bib
